# Generated by Django 3.2.4 on 2021-06-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_locations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityindexdiscriptions',
            name='index',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='report.index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestions',
            name='index',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='report.index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestions',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='report.location'),
            preserve_default=False,
        ),
    ]
