# Generated by Django 3.2.4 on 2021-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210617_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttoday',
            name='score',
            field=models.FloatField(),
        ),
    ]
