# Generated by Django 3.2.4 on 2021-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reporttoday_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityindexdiscriptions',
            name='greaterThan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activityindexdiscriptions',
            name='lessThan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='greaterThan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='lessThan',
            field=models.FloatField(),
        ),
    ]
