# Generated by Django 3.2.4 on 2021-06-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_token'),
        ('report', '0006_auto_20210620_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDate', models.DateTimeField()),
                ('score', models.FloatField()),
                ('steps', models.IntegerField()),
                ('screenTime', models.IntegerField()),
                ('sleepTime', models.IntegerField()),
                ('indexHours', models.TextField()),
                ('activityIndexDiscriptions', models.ManyToManyField(blank=True, to='report.ActivityIndexDiscriptions')),
                ('suggestions', models.ManyToManyField(blank=True, to='report.Suggestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportToday',
        ),
    ]
