# Generated by Django 3.2.4 on 2021-06-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210629_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='dateDate',
            new_name='dateDay',
        ),
    ]
