# Generated by Django 3.2.4 on 2021-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_rename_datedate_report_dateday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='suggestions',
            name='title',
            field=models.CharField(default='discription', max_length=100),
            preserve_default=False,
        ),
    ]
