# Generated by Django 3.2.4 on 2021-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20210715_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='imageUrl',
            field=models.CharField(default='https://images.newindianexpress.com/uploads/user/imagelibrary/2020/2/4/w1200X800/Yoga_d12.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
