# Generated by Django 3.2.4 on 2021-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useruid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age', models.IntegerField()),
                ('quiz_answer_string', models.CharField(max_length=100)),
                ('calculated_scores', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='uid',
            new_name='useruid',
        ),
    ]
