# Generated by Django 3.2.4 on 2021-07-16 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_end', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RawActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soundType', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('screenTime', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DetailActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soundType', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenTime', models.IntegerField()),
                ('is_mocked', models.BooleanField(default=False)),
                ('steps', models.IntegerField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.index')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
