# Generated by Django 3.2.4 on 2021-09-27 07:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_string', models.CharField(max_length=100)),
                ('useruid', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 10, 7, 15181))),
            ],
        ),
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useruid', models.CharField(max_length=100)),
                ('usageString', models.TextField()),
                ('timestamp', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='screenTime',
            new_name='amplitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='soundType',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetailActivity',
        ),
    ]
