# Generated by Django 3.2.4 on 2021-09-30 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_survey_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 19, 22, 13, 105270)),
        ),
    ]
