# Generated by Django 3.2.4 on 2021-06-09 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210609_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
