# Generated by Django 3.2.4 on 2021-06-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rawactivity_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('index', models.CharField(max_length=20)),
                ('indexid', models.IntegerField()),
                ('is_mocked', models.BooleanField(default=False)),
                ('rawActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.rawactivity')),
            ],
        ),
    ]
