# Generated by Django 3.2.4 on 2021-06-11 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('activity', '0004_detailactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailactivity',
            name='rawActivity',
        ),
        migrations.AddField(
            model_name='detailactivity',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailactivity',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailactivity',
            name='soundType',
            field=models.CharField(default='speech', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailactivity',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
            preserve_default=False,
        ),
    ]
