# Generated by Django 3.2.4 on 2021-09-30 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_survey_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='survey',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 19, 25, 22, 150007)),
        ),
    ]
