# Generated by Django 3.2.4 on 2021-06-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210617_1202'),
        ('activity', '0006_sleepevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailactivity',
            name='indexid',
        ),
        migrations.AlterField(
            model_name='detailactivity',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.index'),
        ),
        migrations.AlterField(
            model_name='detailactivity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location'),
        ),
    ]
