# Generated by Django 3.2.4 on 2021-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20210617_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailactivity',
            name='screenStatus',
            field=models.CharField(default="On", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawactivity',
            name='screenStatus',
            field=models.CharField(default="on", max_length=50),
            preserve_default=False,
        ),
    ]
