# Generated by Django 3.2.4 on 2021-09-30 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_survey_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='moods',
        ),
        migrations.AlterField(
            model_name='survey',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 12, 48, 59, 276318)),
        ),
    ]
