# Generated by Django 3.2.4 on 2021-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20210617_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailactivity',
            name='screenStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rawactivity',
            name='screenStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
