# Generated by Django 3.2.4 on 2021-09-30 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20210930_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 15, 44, 45, 581904)),
        ),
    ]
