# Generated by Django 3.2.4 on 2021-06-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20210617_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailactivity',
            name='screenStatus',
        ),
        migrations.RemoveField(
            model_name='rawactivity',
            name='screenStatus',
        ),
        migrations.AddField(
            model_name='detailactivity',
            name='screenTime',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawactivity',
            name='screenTime',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
