# Generated by Django 3.2.4 on 2021-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20210619_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailactivity',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawactivity',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
