# Generated by Django 3.2.4 on 2021-06-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20210622_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawactivity',
            name='screenTime',
            field=models.IntegerField(),
        ),
    ]
