# Generated by Django 3.2.4 on 2021-06-29 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_detailactivity_screentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
